/**
 * The built-in provider descriptors, as the builds see them.
 *
 * `providers/*.json` at the repo root is the single source of truth for which
 * sites the shipped bundles support: this module compiles them into
 * `src/providers/builtin.gen.ts` (exact bytes plus their sha256, so a built-in
 * can be compared with what a server offers) and derives the extension's
 * `content_scripts.matches` and the userscript's `@match` lines from them.
 *
 * Run directly to regenerate: `node scripts/providers.mjs`. The builds call
 * `writeGenerated()` first, and providers.test.ts fails when the committed
 * file is stale, so a descriptor edit cannot ship half-applied.
 *
 * Node runs the TypeScript validator directly (type stripping), so the build
 * rejects exactly what a client would.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseDescriptor } from '../src/providers/descriptor.ts';

const here = dirname(fileURLToPath(import.meta.url));
export const PROVIDERS_DIR = join(here, '..', '..', '..', 'providers');
export const GENERATED = join(here, '..', 'src', 'providers', 'builtin.gen.ts');

/** Every built-in, validated with its examples run. Throws on the first bad one. */
export function loadBuiltins(dir = PROVIDERS_DIR) {
  const files = readdirSync(dir).filter((f) => f.endsWith('.json')).sort();
  const out = [];
  const ids = new Set();
  for (const file of files) {
    const source = readFileSync(join(dir, file), 'utf8');
    const r = parseDescriptor(source);
    if (!r.ok) throw new Error(`providers/${file} is invalid:\n  ${r.errors.join('\n  ')}`);
    const id = r.provider.id;
    if (ids.has(id)) throw new Error(`providers/${file}: id "${id}" is used twice`);
    ids.add(id);
    const sha256 = createHash('sha256').update(source, 'utf8').digest('hex');
    out.push({ file, id, source, sha256, provider: r.provider });
  }
  return out;
}

export function renderGenerated(builtins) {
  const rows = builtins.map((b) =>
    `  {\n    file: ${JSON.stringify(b.file)},\n    sha256: ${JSON.stringify(b.sha256)},\n    source: ${JSON.stringify(b.source)},\n  },`);
  return [
    '// Generated by client/core/scripts/providers.mjs from providers/*.json. Do not edit;',
    '// edit the JSON and run `node scripts/providers.mjs` (the builds do it for you).',
    '',
    'export const BUILTIN_SOURCES: ReadonlyArray<{ file: string; sha256: string; source: string }> = [',
    ...rows,
    '];',
    '',
  ].join('\n');
}

export function writeGenerated(dir = PROVIDERS_DIR) {
  const builtins = loadBuiltins(dir);
  const text = renderGenerated(builtins);
  let old = '';
  try { old = readFileSync(GENERATED, 'utf8'); } catch { /* first run */ }
  if (old !== text) writeFileSync(GENERATED, text);
  return builtins;
}

/**
 * Match patterns for the pages the shims run on: https only, one per page
 * host, in descriptor order. `*.example.com` is a valid match-pattern host in
 * both Chrome and Tampermonkey.
 */
export function matchPatterns(builtins) {
  const out = [];
  for (const b of builtins) {
    for (const h of b.provider.pageHosts) {
      const p = `https://${h}/*`;
      if (!out.includes(p)) out.push(p);
    }
  }
  return out;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const b = writeGenerated();
  console.log(`providers: ${b.map((x) => `${x.file} (${x.id})`).join(', ')} -> ${GENERATED}`);
}
